/* DentalSeptiņi — i18n + content data */

const SERVICES = [
  {
    id: "treatment",
    icon: "T",
    lv: { name: "Zobu ārstēšana", short: "Plombēšana, kariesa ārstēšana un saudzīga pieeja katram zobam.",
          long: "Mūsdienīga kariesa ārstēšana ar helio­materiāliem, mikroskopu un saudzīgu Brix 3000 metodi. Strādājam zem koferdama – sterili un precīzi.",
          bullets: ["Helio­materiāli un kompozītmateriāli","Mikroskopiskā precizitāte","Saudzīga Brix 3000 metode","Vienreizēja anestēzija"] },
    ru: { name: "Лечение зубов", short: "Пломбирование, лечение кариеса и бережный подход к каждому зубу.",
          long: "Современное лечение кариеса с гелиоматериалами, микроскопом и щадящим методом Brix 3000. Работаем под коффердамом — стерильно и точно.",
          bullets: ["Гелио- и композитные материалы","Работа под микроскопом","Щадящая методика Brix 3000","Однократная анестезия"] },
    en: { name: "Restorative care", short: "Fillings, caries treatment and a gentle approach to every tooth.",
          long: "Modern caries treatment with helio-composites, microscope precision and the gentle Brix 3000 method. We work under rubber dam — sterile and accurate.",
          bullets: ["Helio composites","Microscope precision","Gentle Brix 3000 technique","Single anaesthesia"] },
    priceFrom: 50,
  },
  {
    id: "hygiene",
    icon: "H",
    lv: { name: "Zobu higiēna", short: "Profesionāla mutes higiēna ar ultraskaņu un Air-flow.",
          long: "Pilna mutes higiēna ar ultraskaņu, Air-flow un fluora apstrādi – pamats veselīgam smaidam un balti­nāšanai.",
          bullets: ["Ultraskaņas tīrīšana","Air-flow apstrāde","Tiefenfluorīds","Konsultācija par mājas kopšanu"] },
    ru: { name: "Гигиена зубов", short: "Профессиональная гигиена с ультразвуком и Air-flow.",
          long: "Полная гигиена полости рта с ультразвуком, Air-flow и фторированием — основа здоровой улыбки и подготовка к отбеливанию.",
          bullets: ["Ультразвуковая чистка","Обработка Air-flow","Tiefenfluorid","Подбор домашнего ухода"] },
    en: { name: "Dental hygiene", short: "Professional oral hygiene with ultrasound and Air-flow.",
          long: "Full mouth hygiene with ultrasound, Air-flow and fluoride treatment — the foundation for a healthy smile and whitening.",
          bullets: ["Ultrasound cleaning","Air-flow polishing","Tiefenfluoride","Home-care consultation"] },
    priceFrom: 60,
  },
  {
    id: "implants",
    icon: "I",
    lv: { name: "Zobu implantācija", short: "Straumann, Neodent un MegaGen — implanti pa vienai vizītei.",
          long: "Implantācija ar ķirurģisko gidu: caur nelielu caurumu, bez smaganu griešanas. Iespējama uzreizēja noslodze ar pagaidu kroni.",
          bullets: ["Straumann SLA / SLActive","Neodent (Šveice)","MegaGen (Koreja)","Ķirurģiskais gids"] },
    ru: { name: "Имплантация", short: "Straumann, Neodent и MegaGen — имплант за один визит.",
          long: "Имплантация с хирургическим шаблоном: через небольшое отверстие, без разреза десны. Возможна немедленная нагрузка временной коронкой.",
          bullets: ["Straumann SLA / SLActive","Neodent (Швейцария)","MegaGen (Корея)","Хирургический шаблон"] },
    en: { name: "Implants", short: "Straumann, Neodent and MegaGen — implants in a single visit.",
          long: "Guided implantology: through a small opening, no gum cutting. Immediate loading with a temporary crown is possible.",
          bullets: ["Straumann SLA / SLActive","Neodent (Switzerland)","MegaGen (Korea)","Surgical guide"] },
    priceFrom: 600,
  },
  {
    id: "prosth",
    icon: "P",
    lv: { name: "Protezēšana", short: "Cirkonija, metālkeramika, vinīri un luminīri.",
          long: "Pilnas un daļējās protēzes, cirkonija un metālkeramikas kroņi, porcelāna vinīri un luminīri — pēc digitāla 3Shape skenējuma.",
          bullets: ["Cirkonija kroņi","Porcelāna vinīri","CAD/CAM izgatavošana","Digitāls 3Shape skenējums"] },
    ru: { name: "Протезирование", short: "Цирконий, металлокерамика, виниры и люминиры.",
          long: "Полные и частичные протезы, циркониевые и металлокерамические коронки, фарфоровые виниры и люминиры — по цифровому слепку 3Shape.",
          bullets: ["Циркониевые коронки","Фарфоровые виниры","CAD/CAM производство","Цифровой слепок 3Shape"] },
    en: { name: "Prosthetics", short: "Zirconia, ceramic crowns, veneers and lumineers.",
          long: "Full and partial dentures, zirconia and ceramic-metal crowns, porcelain veneers and lumineers — from a digital 3Shape scan.",
          bullets: ["Zirconia crowns","Porcelain veneers","CAD/CAM milling","Digital 3Shape scan"] },
    priceFrom: 350,
  },
  {
    id: "whitening",
    icon: "W",
    lv: { name: "Zobu balināšana", short: "Philips ZOOM un foto­balināšana viena seansa laikā.",
          long: "Foto­balināšana ārsta kabinetā 20 minūtēs un sertificēta Philips ZOOM procedūra. Pieejamas individuālās balināšanas kapes.",
          bullets: ["Philips ZOOM","Foto­balināšana 20 min.","Individuālas kapes","Sensitivitātes apstrāde"] },
    ru: { name: "Отбеливание", short: "Philips ZOOM и фотоотбеливание за один визит.",
          long: "Фотоотбеливание в кабинете врача за 20 минут и сертифицированная процедура Philips ZOOM. Доступны индивидуальные капы.",
          bullets: ["Philips ZOOM","Фото­отбеливание 20 мин.","Индивидуальные капы","Снятие чувствительности"] },
    en: { name: "Whitening", short: "Philips ZOOM and in-office photo whitening in a single visit.",
          long: "20-minute in-office photo whitening and certified Philips ZOOM procedure. Custom whitening trays available.",
          bullets: ["Philips ZOOM","20-min photo whitening","Custom trays","Sensitivity care"] },
    priceFrom: 80,
  },
  {
    id: "surgery",
    icon: "S",
    lv: { name: "Zobu ķirurģija", short: "Zoba izraušana, ķirurģija un APRF reģenerācija.",
          long: "Saudzīga zobu izraušana ar moderno anestēziju, paradontozes ārstēšana un brūču reģenerācija ar APRF tehnoloģiju.",
          bullets: ["APRF reģenerācija","Atraumatiska izraušana","Paradontoloģija","PeriAcryl 90HV"] },
    ru: { name: "Хирургия", short: "Удаление зуба, хирургия и регенерация APRF.",
          long: "Бережное удаление с современной анестезией, лечение пародонтоза и регенерация ран по технологии APRF.",
          bullets: ["Регенерация APRF","Атравматичное удаление","Пародонтология","PeriAcryl 90HV"] },
    en: { name: "Surgery", short: "Tooth extraction, surgery and APRF regeneration.",
          long: "Atraumatic extractions with modern anaesthesia, periodontal care and wound regeneration with APRF technology.",
          bullets: ["APRF regeneration","Atraumatic extraction","Periodontology","PeriAcryl 90HV"] },
    priceFrom: 50,
  },
  {
    id: "endo",
    icon: "E",
    lv: { name: "Endodontija", short: "Sakņu kanālu ārstēšana ar apex lokatoru.",
          long: "Sakņu kanālu ārstēšana ar rotējošo sistēmu, apex lokatoru un mikroskopu. Saglabājam dabīgo zobu, kur tas iespējams.",
          bullets: ["Rotējošā sistēma","Apex lokators","Koferdams","Mikroskops"] },
    ru: { name: "Эндодонтия", short: "Лечение корневых каналов с апекс-локатором.",
          long: "Лечение корневых каналов с ротационной системой, апекс-локатором и микроскопом. Сохраняем зуб там, где это возможно.",
          bullets: ["Ротационная система","Апекс-локатор","Коффердам","Микроскоп"] },
    en: { name: "Endodontics", short: "Root canal treatment with apex locator.",
          long: "Root canal therapy with rotary instruments, apex locator and microscope. We save the natural tooth wherever possible.",
          bullets: ["Rotary system","Apex locator","Rubber dam","Microscope"] },
    priceFrom: 120,
  },
  {
    id: "kids",
    icon: "K",
    lv: { name: "Bērnu zobārstniecība", short: "Saudzīga pieeja maziem pacientiem.",
          long: "Bērnu konsultācija, profilakse un ārstēšana mierīgā vidē. Bērnu panorāmas rentgens un saudzīga sedācija.",
          bullets: ["Bērnu panorāma 15 €","Fluora apstrāde","Profilaktiska tīrīšana","Mierīga atmosfēra"] },
    ru: { name: "Детская стоматология", short: "Бережный подход к маленьким пациентам.",
          long: "Детская консультация, профилактика и лечение в спокойной обстановке. Детская панорама и щадящая седация.",
          bullets: ["Детская панорама 15 €","Фторирование","Профилактическая чистка","Спокойная атмосфера"] },
    en: { name: "Children", short: "A gentle approach for young patients.",
          long: "Children's consultations, prevention and treatment in a calm setting. Paediatric panoramic X-ray and gentle sedation.",
          bullets: ["Paediatric pano €15","Fluoride application","Preventive cleaning","Calm atmosphere"] },
    priceFrom: 10,
  },
];

const TEAM = [
  {
    id: "grazina",
    name: "Dr. Gražina Šandroha",
    role: { lv: "Zobārste, klīnikas dibinātāja", ru: "Стоматолог, основатель клиники", en: "Dentist, clinic founder" },
    since: 1993,
    bio: {
      lv: "Latvijas Universitātes Stomatoloģijas fakultātes absolvente (1993). Specializējas implantoloģijā un audu plastiskajā ķirurģijā. Pastāvīgi apmeklē starptautiskus seminārus un meistarklases.",
      ru: "Выпускница стоматологического факультета Латвийского университета (1993). Специализация — имплантология и пластика мягких тканей. Постоянно посещает международные семинары и мастер-классы.",
      en: "Graduate of the University of Latvia (Faculty of Stomatology, 1993). Specialises in implantology and soft-tissue plastic surgery. A regular attendee of international seminars and masterclasses."
    },
    tags: ["Implantology","Surgery","Aesthetic"],
  },
  {
    id: "katrina",
    name: "Katrīna Krastiņa",
    role: { lv: "Higiēniste", ru: "Гигиенист", en: "Dental hygienist" },
    since: 2018,
    bio: {
      lv: "Rīgas Stradiņa Universitātes absolvente. Specializējas pilnā mutes dobuma higiēnā un zobu balināšanā. Turpina pilnveidoties — kursi katru gadu.",
      ru: "Выпускница Рижского университета им. Страдыня. Специализация — полная гигиена полости рта и отбеливание. Ежегодно проходит профильные курсы.",
      en: "Graduate of Rīga Stradiņš University. Specialises in full-mouth hygiene and whitening. Continues professional development — yearly courses."
    },
    tags: ["Hygiene","Whitening","Air-flow"],
  },
  {
    id: "marite",
    name: "Mārīte Soroko",
    role: { lv: "Zobārsta asistente", ru: "Ассистент стоматолога", en: "Dental assistant" },
    since: 2019,
    bio: {
      lv: "Uzmanīga, kārtīga un atbildīga asistente, kas vienmēr orientēta uz pacienta komfortu. Atbild par procedūras kabineta sagatavošanu un sterilitāti.",
      ru: "Внимательный, аккуратный и ответственный ассистент, всегда ориентированный на комфорт пациента. Отвечает за подготовку кабинета и стерильность.",
      en: "Attentive, organised and reliable assistant, focused on patient comfort. Responsible for preparing the cabinet and sterility."
    },
    tags: ["Patient care","Sterility","Support"],
  },
  {
    id: "anna",
    name: "Anna Liepiņa",
    role: { lv: "Ortodonts", ru: "Ортодонт", en: "Orthodontist" },
    since: 2015,
    bio: {
      lv: "Orālā ortodontija pieaugušajiem un bērniem. Strādā ar Invisalign caurspīdīgajām kapēm un klasiskām breketēm.",
      ru: "Ортодонтия для взрослых и детей. Работает с прозрачными элайнерами Invisalign и классическими брекетами.",
      en: "Adult and paediatric orthodontics. Works with Invisalign clear aligners and classic braces."
    },
    tags: ["Invisalign","Braces","Bite correction"],
  },
];

const PRICING = [
  { cat: { lv: "Konsultācijas", ru: "Консультации", en: "Consultations" }, items: [
    { lv: "Ārsta konsultācija", ru: "Консультация врача", en: "Doctor's consultation", price: "10 – 20" },
  ]},
  { cat: { lv: "Diagnostika", ru: "Диагностика", en: "Diagnostics" }, items: [
    { lv: "Rentgens (digitālais) 2-3 zobiem", ru: "Цифровой рентген 2–3 зубов", en: "Digital X-ray 2–3 teeth", price: "10" },
    { lv: "3Shape intraorālais skenējums (abi žokļi)", ru: "Интраоральный скан 3Shape (обе челюсти)", en: "3Shape intraoral scan (both jaws)", price: "30" },
    { lv: "Diagnostika ar MI programmatūru", ru: "Диагностика с ИИ-программой", en: "AI-assisted diagnostics", price: "10" },
    { lv: "Bērnu panorāmas rentgens", ru: "Детский панорамный снимок", en: "Paediatric panoramic X-ray", price: "15" },
    { lv: "OPM (panorāmas RTG) uz e-pastu", ru: "Панорамный снимок на e-mail", en: "Panoramic X-ray (e-mail)", price: "20" },
    { lv: "3D pilns (abi žokļi)", ru: "3D полный (обе челюсти)", en: "3D full (both jaws)", price: "60" },
    { lv: "3D viens žoklis", ru: "3D одна челюсть", en: "3D one jaw", price: "35" },
  ]},
  { cat: { lv: "Zobu ķirurģija", ru: "Хирургия", en: "Surgery" }, items: [
    { lv: "Paradontozes ārstēšana", ru: "Лечение пародонтоза", en: "Periodontal treatment", price: "20" },
    { lv: "Brūces vietā APRF ievietošana", ru: "Установка APRF в рану", en: "APRF placement in wound", price: "50" },
    { lv: "Viensakņu zoba izraušana", ru: "Удаление однокорневого зуба", en: "Single-root extraction", price: "50" },
    { lv: "Divsakņu zoba izraušana", ru: "Удаление двукорневого зуба", en: "Two-root extraction", price: "no 60" },
    { lv: "Trīssakņu zoba izraušana", ru: "Удаление трёхкорневого зуба", en: "Three-root extraction", price: "no 90" },
    { lv: "Anestēzija", ru: "Анестезия", en: "Anaesthesia", price: "10" },
    { lv: "Šuves uzlikšana / noņemšana", ru: "Швы / снятие швов", en: "Sutures / removal", price: "10" },
    { lv: "Brūces apstrāde ar PeriAcryl", ru: "Обработка раны PeriAcryl", en: "PeriAcryl wound treatment", price: "20" },
  ]},
  { cat: { lv: "Endodontija (kanāli)", ru: "Эндодонтия (каналы)", en: "Endodontics (root canals)" }, items: [
    { lv: "Sakņu kanālu ārstēšana", ru: "Лечение корневых каналов", en: "Root canal treatment", price: "120 – 350" },
    { lv: "Sakņu kanālu pārārstēšana", ru: "Перелечивание каналов", en: "Root canal retreatment", price: "250 – 400" },
    { lv: "Apex lokators", ru: "Апекс-локатор", en: "Apex locator", price: "15" },
    { lv: "Koferdama uzlikšana", ru: "Установка коффердама", en: "Rubber dam placement", price: "15" },
    { lv: "1 kanāla pildīšana", ru: "Пломбировка 1 канала", en: "1-canal obturation", price: "20" },
    { lv: "3 kanālu pildīšana", ru: "Пломбировка 3 каналов", en: "3-canal obturation", price: "60" },
    { lv: "Stiklašķiedras tapas fiksācija", ru: "Фиксация стекловолоконного штифта", en: "Fibre-glass post", price: "20" },
  ]},
  { cat: { lv: "Implantoloģija", ru: "Имплантология", en: "Implantology" }, items: [
    { lv: "Implants Neodent", ru: "Имплант Neodent", en: "Neodent implant", price: "600" },
    { lv: "Implants MegaGen", ru: "Имплант MegaGen", en: "MegaGen implant", price: "650" },
    { lv: "Implants Straumann SLA", ru: "Имплант Straumann SLA", en: "Straumann SLA implant", price: "700" },
    { lv: "Implants Straumann SLActive BLX", ru: "Имплант Straumann SLActive BLX", en: "Straumann SLActive BLX", price: "800" },
    { lv: "Metālkeramikas kronis uz implanta", ru: "Металлокерамическая коронка на импланте", en: "Ceramic-metal crown on implant", price: "500" },
    { lv: "Cirkonija kronis uz implanta", ru: "Циркониевая коронка на импланте", en: "Zirconia crown on implant", price: "550" },
    { lv: "Kaula augmentācija", ru: "Костная аугментация", en: "Bone augmentation", price: "500" },
    { lv: "APRF", ru: "APRF", en: "APRF", price: "80" },
  ]},
  { cat: { lv: "Terapija", ru: "Терапия", en: "Therapy" }, items: [
    { lv: "Zobu pārklāšana ar heliomateriālu", ru: "Покрытие гелиоматериалом", en: "Helio-composite coating", price: "80" },
    { lv: "Vienas virsmas plomba (helio)", ru: "Пломба 1 поверхности (гелио)", en: "1-surface filling (helio)", price: "50" },
    { lv: "Divu virsmu plomba (helio)", ru: "Пломба 2 поверхностей (гелио)", en: "2-surface filling (helio)", price: "60" },
    { lv: "Trīs virsmu plomba (helio)", ru: "Пломба 3 поверхностей (гелио)", en: "3-surface filling (helio)", price: "70" },
    { lv: "Zoba pilnā atjaunošana", ru: "Полное восстановление зуба", en: "Full tooth restoration", price: "80" },
    { lv: "Apstrāde ar Brix 3000", ru: "Обработка Brix 3000", en: "Brix 3000 treatment", price: "30" },
  ]},
  { cat: { lv: "Higiēna un balināšana", ru: "Гигиена и отбеливание", en: "Hygiene & whitening" }, items: [
    { lv: "Pilnā mutes higiēna + ultraskaņa + fluors", ru: "Полная гигиена + ультразвук + фтор", en: "Full hygiene + ultrasound + fluoride", price: "60" },
    { lv: "Zobu pārklāšana ar tiefenfluoridu", ru: "Покрытие Tiefenfluorid", en: "Tiefenfluoride application", price: "50" },
    { lv: "Foto­balināšana (20 min.)", ru: "Фото­отбеливание (20 мин.)", en: "Photo whitening (20 min.)", price: "80" },
    { lv: "Philips ZOOM balināšana", ru: "Отбеливание Philips ZOOM", en: "Philips ZOOM whitening", price: "320" },
    { lv: "Zobu dekors", ru: "Зубной декор", en: "Tooth jewellery", price: "25" },
  ]},
  { cat: { lv: "Protezēšana — kroņi un vinīri", ru: "Протезирование — коронки и виниры", en: "Prosthetics — crowns & veneers" }, items: [
    { lv: "Cirkonija kronis", ru: "Циркониевая коронка", en: "Zirconia crown", price: "450" },
    { lv: "Cirkonija kronis ar keramikas pārklājumu", ru: "Циркониевая коронка с керамикой", en: "Zirconia + ceramic crown", price: "500" },
    { lv: "Metālkeramikas kronis", ru: "Металлокерамическая коронка", en: "Ceramic-metal crown", price: "350" },
    { lv: "Porcelāna vinīrs", ru: "Фарфоровый винир", en: "Porcelain veneer", price: "350" },
    { lv: "Luminīrs", ru: "Люминир", en: "Lumineer", price: "600" },
    { lv: "Cirkonija inleja / onleja", ru: "Циркониевая инлей / онлей", en: "Zirconia inlay / onlay", price: "200 / 300" },
    { lv: "Pagaidu kronis (laboratorijā)", ru: "Временная коронка (лаборатория)", en: "Temporary crown (lab)", price: "100" },
  ]},
  { cat: { lv: "Kapes un izņemamās protēzes", ru: "Капы и съёмные протезы", en: "Trays & removable dentures" }, items: [
    { lv: "Balināšanas kapes", ru: "Капы для отбеливания", en: "Whitening trays", price: "150" },
    { lv: "Nakts kape (divslāņu)", ru: "Ночная капа (двухслойная)", en: "Night guard (dual layer)", price: "120" },
    { lv: "Sporta kape", ru: "Спортивная капа", en: "Sports mouthguard", price: "130" },
    { lv: "Bokseru kape (divslāņu, frontāli)", ru: "Боксёрская капа (двухслойная)", en: "Boxer mouthguard (dual layer)", price: "170" },
    { lv: "Izņemamā protēze (daļējā)", ru: "Частичный съёмный протез", en: "Partial removable denture", price: "220" },
    { lv: "Izņemamā protēze (pilnā)", ru: "Полный съёмный протез", en: "Full removable denture", price: "380" },
    { lv: "Elastīgā parciālā protēze", ru: "Эластичный частичный протез", en: "Flexible partial denture", price: "390" },
  ]},
];

const FAQ = [
  {
    q: { lv: "Ar kurām apdrošināšanas kompānijām jūs sadarbojaties?", ru: "С какими страховыми компаниями вы работаете?", en: "Which insurance companies do you work with?" },
    a: { lv: "Mēs sadarbojamies ar BALTA, BTA, Gjensidige, ERGO, Seesam, IF un COMPENSA. Pirms vizītes pārbaudām polises segumu un sagatavojam dokumentus.",
         ru: "Мы работаем с BALTA, BTA, Gjensidige, ERGO, Seesam, IF и COMPENSA. Перед визитом проверим покрытие полиса и подготовим документы.",
         en: "We work with BALTA, BTA, Gjensidige, ERGO, Seesam, IF and COMPENSA. We verify coverage and prepare paperwork before your visit." }
  },
  {
    q: { lv: "Vai pieņemat ar akūtām zobu sāpēm?", ru: "Принимаете ли с острой болью?", en: "Do you accept emergency walk-ins?" },
    a: { lv: "Jā, akūto sāpju pacientus pieņemam darba dienās no 12:00 līdz 14:00. Lūdzu, zvaniet iepriekš: +371 291 135 84.",
         ru: "Да, пациентов с острой болью принимаем в будни с 12:00 до 14:00. Пожалуйста, позвоните заранее: +371 291 135 84.",
         en: "Yes — emergency patients are seen on weekdays from 12:00 to 14:00. Please call ahead at +371 291 135 84." }
  },
  {
    q: { lv: "Kādās valodās jūs konsultējat?", ru: "На каких языках консультируете?", en: "Which languages do you speak?" },
    a: { lv: "Latviešu, krievu un angļu valodā. Pieraksta forma un apraksti ir pieejami visās trīs valodās.",
         ru: "Латышский, русский и английский. Форма записи и описания доступны на всех трёх языках.",
         en: "Latvian, Russian and English. The booking form and content are available in all three languages." }
  },
  {
    q: { lv: "Vai implants tiešām nav sāpīgs?", ru: "Имплантация действительно безболезненна?", en: "Is implant placement really painless?" },
    a: { lv: "Procedūra notiek ar vietējo anestēziju un ķirurģisko gidu — caur nelielu caurumu, bez smaganu griešanas. Lielākā daļa pacientu nākamajā dienā atgriežas darbā.",
         ru: "Процедура проходит под местной анестезией с хирургическим шаблоном — через небольшое отверстие, без разреза десны. Большинство пациентов на следующий день возвращаются к работе.",
         en: "The procedure is done under local anaesthesia using a surgical guide — through a small opening, without cutting the gum. Most patients return to work the next day." }
  },
  {
    q: { lv: "Cik ilgi kalpo cirkonija kronis?", ru: "Сколько служит циркониевая коронка?", en: "How long does a zirconia crown last?" },
    a: { lv: "Pareizi izgatavots un kopts cirkonija kronis kalpo 15 un vairāk gadus. Mēs sniedzam 5 gadu garantiju savam darbam.",
         ru: "Корректно изготовленная и обслуживаемая циркониевая коронка служит 15+ лет. Мы даём 5 лет гарантии на свою работу.",
         en: "A properly made and maintained zirconia crown lasts 15+ years. We provide a 5-year warranty on our work." }
  },
  {
    q: { lv: "Vai jums ir bērnu zobārstniecība?", ru: "Лечите ли детей?", en: "Do you treat children?" },
    a: { lv: "Jā, no 4 gadu vecuma. Pirmā vizīte ir adaptācijas vizīte — bez instrumentiem, lai bērns iepazītu kabinetu.",
         ru: "Да, с 4 лет. Первый визит — адаптационный, без инструментов, чтобы ребёнок познакомился с кабинетом.",
         en: "Yes, from age 4. The first visit is an adaptation visit — no instruments, so the child can get used to the cabinet." }
  },
  {
    q: { lv: "Kā veikt apmaksu?", ru: "Как оплатить?", en: "How can I pay?" },
    a: { lv: "Skaidrā naudā, ar bankas karti vai pārskaitījumu. Apdrošināšanas pacientiem norēķini notiek tieši ar apdrošinātāju.",
         ru: "Наличными, картой или переводом. Для застрахованных пациентов оплата идёт напрямую через страховую.",
         en: "Cash, card or bank transfer. Insured patients are billed directly through the insurer." }
  },
];

const REVIEWS = [
  { author: "Inese B.", source: "Google", rating: 5, lv: "Pārdomāta pieeja, mierīga atmosfēra un pilnībā nesāpīga ārstēšana. Esmu pacients jau 6 gadus.",
    ru: "Внимательный подход, спокойная атмосфера и абсолютно безболезненное лечение. Пациент уже 6 лет.",
    en: "Thoughtful approach, calm atmosphere and completely painless treatment. I have been a patient for 6 years." },
  { author: "Mārtiņš K.", source: "Google", rating: 5, lv: "Implants ielikts pa vienu vizīti, bez sāpēm. Pēc nedēļas — kā nekā nebūtu bijis.",
    ru: "Имплант поставили за один визит, без боли. Через неделю — как будто ничего и не было.",
    en: "Implant placed in a single visit, no pain. A week later it felt like nothing had happened." },
  { author: "Anastasija R.", source: "Google", rating: 5, lv: "Beidzot zobārstniecība bez stresa. Visu pacietīgi paskaidro un piedāvā vairākus risinājumus.",
    ru: "Наконец-то стоматология без стресса. Всё терпеливо объясняют и предлагают несколько решений.",
    en: "Finally dentistry without stress. They explain everything patiently and offer several options." },
  { author: "Jānis P.", source: "Facebook", rating: 5, lv: "Sertificēti speciālisti, modernais aprīkojums un visas apdrošināšanas — kompānija pieņem caur Compensa.",
    ru: "Сертифицированные специалисты, современное оборудование, принимают через Compensa.",
    en: "Certified specialists, modern equipment, accepted my Compensa insurance." },
  { author: "Olga V.", source: "Google", rating: 5, lv: "Higiēna ar Air-flow — debesu un zeme atšķirība no iepriekšējās klīnikas.",
    ru: "Гигиена с Air-flow — небо и земля по сравнению с предыдущей клиникой.",
    en: "Air-flow hygiene — night and day compared to my previous clinic." },
];

const TECH = [
  { lv: { name: "3Shape TRIOS skeneris", desc: "Digitāls intraorāls skenējums 30 sekundēs — bez nepatīkamas masas." },
    ru: { name: "Сканер 3Shape TRIOS", desc: "Цифровой интраоральный скан за 30 секунд — без неприятной массы." },
    en: { name: "3Shape TRIOS scanner", desc: "Digital intraoral scan in 30 seconds — no unpleasant impression material." } },
  { lv: { name: "AI diagnostika", desc: "Mākslīgais intelekts palīdz ārstam neizlaist agrīno kariesu rentgenā." },
    ru: { name: "ИИ-диагностика", desc: "Искусственный интеллект помогает врачу не пропустить ранний кариес на снимке." },
    en: { name: "AI diagnostics", desc: "AI helps the dentist catch early caries on X-rays the eye can miss." } },
  { lv: { name: "APRF tehnoloģija", desc: "Autologa fibrīna reģenerācija — paātrina dziedēšanu pēc implantācijas." },
    ru: { name: "Технология APRF", desc: "Регенерация на собственном фибрине — ускоряет заживление после имплантации." },
    en: { name: "APRF technology", desc: "Autologous fibrin regeneration — speeds up healing after implants." } },
  { lv: { name: "3D CBCT rentgens", desc: "Pilna 3D rekonstrukcija augšžoklim un apakšžoklim plānošanai." },
    ru: { name: "3D КЛКТ-рентген", desc: "Полная 3D реконструкция верхней и нижней челюсти для планирования." },
    en: { name: "3D CBCT X-ray", desc: "Full 3D reconstruction of upper and lower jaw for planning." } },
  { lv: { name: "Brix 3000", desc: "Saudzīga ferments-bāzēta kariesa noņemšana — bez urbja troksņa." },
    ru: { name: "Brix 3000", desc: "Щадящее ферментативное удаление кариеса — без шума бора." },
    en: { name: "Brix 3000", desc: "Gentle enzymatic caries removal — no drill noise." } },
  { lv: { name: "Philips ZOOM", desc: "Sertificēta balināšanas sistēma — līdz 8 toņiem gaišāk." },
    ru: { name: "Philips ZOOM", desc: "Сертифицированная система отбеливания — до 8 тонов светлее." },
    en: { name: "Philips ZOOM", desc: "Certified whitening system — up to 8 shades lighter." } },
];

const INSURERS = ["BALTA","BTA","Gjensidige","ERGO","Seesam","IF","Compensa"];

const NEWS = [
  { date: "08 / 10 / 2025", tag: "Klīnika",
    lv: { title: "PeriAcryl 90HV", body: "Speciāla lime, kas veido aizsargplēvi uz gļotādas. Lietojam periodontoloģijā un ķirurģijā saudzīgākai dzīšanai." },
    ru: { title: "PeriAcryl 90HV", body: "Специальный клей, формирующий защитную плёнку на слизистой. Применяем в пародонтологии и хирургии." },
    en: { title: "PeriAcryl 90HV", body: "A special adhesive forming a protective film on the mucosa. Used in periodontology and surgery for gentler healing." } },
  { date: "26 / 09 / 2025", tag: "Tehnoloģija",
    lv: { title: "3D Shape zobārstniecības skeneris", body: "Mūsu klīnikā ir pieejams viens no modernākajiem intraorāliem skeneriem 3Shape." },
    ru: { title: "Сканер 3D Shape в клинике", body: "В клинике доступен один из самых современных интраоральных сканеров 3Shape." },
    en: { title: "3D Shape intraoral scanner", body: "Our clinic now offers one of the most advanced intraoral scanners — 3Shape." } },
  { date: "12 / 09 / 2025", tag: "APRF",
    lv: { title: "APRF reģenerācija — ko tas dod pacientam", body: "Autologa fibrīna izmantošana ļauj pacientam ātrāk atveseļoties pēc implantācijas un sarežģītām operācijām." },
    ru: { title: "Регенерация APRF — что это даёт пациенту", body: "Использование собственного фибрина пациента ускоряет восстановление после имплантации." },
    en: { title: "APRF regeneration — what it gives the patient", body: "Using the patient's own fibrin speeds up recovery after implants and complex surgery." } },
];

/* generic UI strings */
const STRINGS = {
  lv: {
    "nav.home": "Sākums",
    "nav.services": "Pakalpojumi",
    "nav.team": "Komanda",
    "nav.pricing": "Cenrādis",
    "nav.contacts": "Kontakti",
    "cta.book": "Pieteikties vizītei",
    "cta.bookShort": "Pieteikties",
    "cta.call": "Zvani",
    "cta.allServices": "Visi pakalpojumi",
    "cta.readMore": "Lasīt vairāk",
    "cta.allNews": "Visi jaunumi",
    "cta.viewProfile": "Skatīt profilu",
    "cta.viewPricing": "Atvērt cenrādi",
    "hero.eyebrow": "Zobārstniecības klīnika · Rīga · kopš 2010",
    "hero.title1": "Mūsdienīga zobārst­niecība,",
    "hero.title2": "ar siltu pieskārienu.",
    "hero.lead": "Augstas kvalitātes pakalpojumi — no higiēnas līdz implantoloģijai. Strādājam ar visām lielākajām apdrošināšanas kompānijām Latvijā.",
    "hero.acute": "Akūtās sāpes — darba dienās 12:00 – 14:00",
    "hero.years": "gadu pieredzē",
    "hero.docs": "ārstu komanda",
    "hero.insurers": "apdrošinātāji",
    "hero.warranty": "gadu garantija",
    "section.services": "Mūsu pakalpojumi",
    "section.services.lead": "No higiēnas līdz pilnai protezēšanai — viss zem viena jumta.",
    "section.tech": "Tehnoloģijas",
    "section.tech.lead": "Aprīkojums, kas padara ārstēšanu precīzu un saudzīgu.",
    "section.team": "Mūsu speciālisti",
    "section.team.lead": "Sertificēti ārsti ar Latvijas un starptautisku pieredzi.",
    "section.why": "Kāpēc izvēlēties mūs",
    "section.book": "Piesakies vizītei",
    "section.book.lead": "Aizpildi formu — sazināsimies tava ērtā laikā.",
    "section.reviews": "Pacientu atsauksmes",
    "section.news": "Jaunumi",
    "section.faq": "Bieži uzdotie jautājumi",
    "section.insurers": "Strādājam ar apdrošinātājiem",
    "section.contacts": "Kontakti",
    "why.exp": "20+ gadu pieredze",
    "why.exp.d": "Klīnika darbojas kopš 2010. gada — ar vienu un to pašu kodolu.",
    "why.tech": "Mūsdienīgs aprīkojums",
    "why.tech.d": "3Shape skeneris, AI diagnostika, ķirurģiskais gids un APRF.",
    "why.team": "Pieredzējuši speciālisti",
    "why.team.d": "Sertificēti ārsti ar pastāvīgu starptautisko pilnveidi.",
    "why.warranty": "5 gadu garantija",
    "why.warranty.d": "Garantija visiem protezēšanas un implantāciju darbiem.",
    "why.lang": "LV / RU / EN",
    "why.lang.d": "Konsultējam un dokumentējam visās trijās valodās.",
    "why.acute": "Akūtā palīdzība",
    "why.acute.d": "Darba dienās 12:00 – 14:00 pieņemam ar akūtām sāpēm.",
    "address": "Dzeņu 7/1-97, Rīga, LV-1021",
    "phone1": "+371 291 135 84",
    "phone2": "+371 675 202 59",
    "hours": "P – Pk 09:00 – 19:00 · S 10:00 – 14:00",
    "footer.tagline": "Sertificēti speciālisti, mūsdienīgs aprīkojums, pieejama vide.",
    "footer.legal": "Reģistrācijas Nr. 40203117924",
    "form.name": "Vārds",
    "form.phone": "Telefons",
    "form.email": "E-pasts",
    "form.service": "Pakalpojums",
    "form.doctor": "Ārsts",
    "form.date": "Vēlamais datums",
    "form.time": "Laiks",
    "form.note": "Piezīmes (nav obligāti)",
    "form.consent": "Piekrītu, ka mani dati tiks izmantoti, lai sazinātos par vizīti.",
    "form.submit": "Pieteikt vizīti",
    "form.next": "Tālāk",
    "form.back": "Atpakaļ",
    "form.from": "no",
    "form.priceFrom": "Cena no",
    "form.req": "Lauks ir obligāts",
    "form.phoneInvalid": "Pārbaudi telefona numuru",
    "form.emailInvalid": "Pārbaudi e-pasta adresi",
    "form.success": "Paldies! Sazināsimies tuvākajā laikā.",
    "form.step": "Solis",
    "form.of": "no",
    "form.selService": "Kādu pakalpojumu vēlies?",
    "form.selDoctor": "Pie kura speciālista?",
    "form.selWhen": "Kad tev ir ērti?",
    "form.contact": "Kā ar tevi sazināties?",
    "form.any": "Jebkurš",
    "search.placeholder": "Meklēt pakalpojumu cenrādī…",
    "pricing.eyebrow": "Cenrādis",
    "pricing.title": "Caurspīdīgas cenas, bez slēptiem maksājumiem.",
    "pricing.lead": "Galīgā cena tiek apstiprināta pēc bezmaksas konsultācijas un diagnostikas.",
    "pricing.note": "Visas cenas norādītas eiro (€). Apdrošināšanas pacientiem norēķini notiek tieši ar apdrošinātāju.",
    "services.eyebrow": "Pakalpojumi",
    "services.title": "Viss, kas vajadzīgs jūsu smaidam.",
    "services.lead": "Detalizēts katras procedūras apraksts un sākotnējās cenas.",
    "team.eyebrow": "Komanda",
    "team.title": "Cilvēki, kas par tevi parūpēsies.",
    "team.lead": "Sertificēti speciālisti ar starptautisku pieredzi.",
    "contacts.eyebrow": "Kontakti",
    "contacts.title": "Atnāc ciemos vai sazinies online.",
    "contacts.lead": "Esam Rīgā, ērti sasniedzami ar sabiedrisko transportu.",
    "yearsClinic": "gadu klīnikā",
    "doctorMore": "Vairāk par speciālistu",
    "acuteBanner": "Akūtās zobu sāpes: darba dienās 12:00 – 14:00",
    "acuteCall": "Zvani uzreiz",
    "lang.label": "Valoda",
  },
  ru: {
    "nav.home": "Главная",
    "nav.services": "Услуги",
    "nav.team": "Команда",
    "nav.pricing": "Цены",
    "nav.contacts": "Контакты",
    "cta.book": "Записаться на визит",
    "cta.bookShort": "Записаться",
    "cta.call": "Позвонить",
    "cta.allServices": "Все услуги",
    "cta.readMore": "Подробнее",
    "cta.allNews": "Все новости",
    "cta.viewProfile": "Смотреть профиль",
    "cta.viewPricing": "Открыть прайс",
    "hero.eyebrow": "Стоматологическая клиника · Рига · с 2010",
    "hero.title1": "Современная стоматология,",
    "hero.title2": "с тёплым прикосновением.",
    "hero.lead": "Высококачественные услуги — от гигиены до имплантологии. Работаем со всеми крупными страховыми компаниями Латвии.",
    "hero.acute": "Острая боль — будни 12:00 – 14:00",
    "hero.years": "лет опыта",
    "hero.docs": "врачей в команде",
    "hero.insurers": "страховых партнёров",
    "hero.warranty": "лет гарантии",
    "section.services": "Наши услуги",
    "section.services.lead": "От гигиены до полного протезирования — всё под одной крышей.",
    "section.tech": "Технологии",
    "section.tech.lead": "Оборудование, которое делает лечение точным и щадящим.",
    "section.team": "Наши специалисты",
    "section.team.lead": "Сертифицированные врачи с латвийским и международным опытом.",
    "section.why": "Почему выбирают нас",
    "section.book": "Запись на визит",
    "section.book.lead": "Заполните форму — свяжемся в удобное время.",
    "section.reviews": "Отзывы пациентов",
    "section.news": "Новости",
    "section.faq": "Часто задаваемые вопросы",
    "section.insurers": "Работаем со страховыми",
    "section.contacts": "Контакты",
    "why.exp": "20+ лет опыта",
    "why.exp.d": "Клиника работает с 2010 года — с тем же сильным ядром команды.",
    "why.tech": "Современное оборудование",
    "why.tech.d": "Сканер 3Shape, ИИ-диагностика, хирургический шаблон, APRF.",
    "why.team": "Опытные специалисты",
    "why.team.d": "Сертифицированные врачи с регулярным международным обучением.",
    "why.warranty": "5 лет гарантии",
    "why.warranty.d": "Гарантия на все работы по протезированию и имплантации.",
    "why.lang": "LV / RU / EN",
    "why.lang.d": "Консультируем и оформляем документы на трёх языках.",
    "why.acute": "Острая помощь",
    "why.acute.d": "В будни с 12:00 до 14:00 принимаем с острой болью.",
    "address": "Ул. Дзеню 7/1-97, Рига, LV-1021",
    "phone1": "+371 291 135 84",
    "phone2": "+371 675 202 59",
    "hours": "Пн – Пт 09:00 – 19:00 · Сб 10:00 – 14:00",
    "footer.tagline": "Сертифицированные специалисты, современное оборудование, доступная среда.",
    "footer.legal": "Регистрационный № 40203117924",
    "form.name": "Имя",
    "form.phone": "Телефон",
    "form.email": "E-mail",
    "form.service": "Услуга",
    "form.doctor": "Врач",
    "form.date": "Желаемая дата",
    "form.time": "Время",
    "form.note": "Комментарий (не обязательно)",
    "form.consent": "Согласен(а) на обработку данных для связи по визиту.",
    "form.submit": "Записаться",
    "form.next": "Далее",
    "form.back": "Назад",
    "form.from": "от",
    "form.priceFrom": "Цена от",
    "form.req": "Поле обязательно",
    "form.phoneInvalid": "Проверьте номер телефона",
    "form.emailInvalid": "Проверьте e-mail",
    "form.success": "Спасибо! Свяжемся с вами в ближайшее время.",
    "form.step": "Шаг",
    "form.of": "из",
    "form.selService": "Какая услуга нужна?",
    "form.selDoctor": "К какому специалисту?",
    "form.selWhen": "Когда вам удобно?",
    "form.contact": "Как с вами связаться?",
    "form.any": "Любой",
    "search.placeholder": "Найти услугу в прайсе…",
    "pricing.eyebrow": "Прайс-лист",
    "pricing.title": "Прозрачные цены, без скрытых платежей.",
    "pricing.lead": "Финальная стоимость подтверждается после бесплатной консультации и диагностики.",
    "pricing.note": "Все цены указаны в евро (€). Для застрахованных пациентов расчёт идёт напрямую через страховую.",
    "services.eyebrow": "Услуги",
    "services.title": "Всё, что нужно вашей улыбке.",
    "services.lead": "Подробное описание каждой процедуры и стартовые цены.",
    "team.eyebrow": "Команда",
    "team.title": "Люди, которые позаботятся о вас.",
    "team.lead": "Сертифицированные специалисты с международным опытом.",
    "contacts.eyebrow": "Контакты",
    "contacts.title": "Приходите в гости или свяжитесь онлайн.",
    "contacts.lead": "Мы в Риге, удобно добираться общественным транспортом.",
    "yearsClinic": "лет в клинике",
    "doctorMore": "Подробнее о специалисте",
    "acuteBanner": "Острая зубная боль: будни 12:00 – 14:00",
    "acuteCall": "Позвонить сейчас",
    "lang.label": "Язык",
  },
  en: {
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.team": "Team",
    "nav.pricing": "Pricing",
    "nav.contacts": "Contacts",
    "cta.book": "Book an appointment",
    "cta.bookShort": "Book a visit",
    "cta.call": "Call us",
    "cta.allServices": "All services",
    "cta.readMore": "Read more",
    "cta.allNews": "All news",
    "cta.viewProfile": "View profile",
    "cta.viewPricing": "Open price list",
    "hero.eyebrow": "Dental clinic · Riga · since 2010",
    "hero.title1": "Modern dentistry,",
    "hero.title2": "with a warm touch.",
    "hero.lead": "High-quality care — from hygiene to implantology. We work with all major Latvian insurance companies.",
    "hero.acute": "Acute pain — weekdays 12:00 – 14:00",
    "hero.years": "years of experience",
    "hero.docs": "specialists on the team",
    "hero.insurers": "insurance partners",
    "hero.warranty": "year warranty",
    "section.services": "Our services",
    "section.services.lead": "From hygiene to full prosthetics — everything under one roof.",
    "section.tech": "Technology",
    "section.tech.lead": "Equipment that makes treatment precise and gentle.",
    "section.team": "Our specialists",
    "section.team.lead": "Certified doctors with Latvian and international experience.",
    "section.why": "Why choose us",
    "section.book": "Book your visit",
    "section.book.lead": "Fill in the form — we'll get back to you at a convenient time.",
    "section.reviews": "Patient reviews",
    "section.news": "News",
    "section.faq": "Frequently asked questions",
    "section.insurers": "Insurance partners",
    "section.contacts": "Contacts",
    "why.exp": "20+ years of practice",
    "why.exp.d": "The clinic has been operating since 2010 — with the same strong core team.",
    "why.tech": "Modern equipment",
    "why.tech.d": "3Shape scanner, AI diagnostics, surgical guide and APRF.",
    "why.team": "Experienced specialists",
    "why.team.d": "Certified doctors with regular international training.",
    "why.warranty": "5-year warranty",
    "why.warranty.d": "Warranty on all prosthetic and implant work.",
    "why.lang": "LV / RU / EN",
    "why.lang.d": "We consult and document in all three languages.",
    "why.acute": "Emergency care",
    "why.acute.d": "Acute-pain walk-ins, weekdays 12:00 – 14:00.",
    "address": "Dzeņu 7/1-97, Riga, LV-1021",
    "phone1": "+371 291 135 84",
    "phone2": "+371 675 202 59",
    "hours": "Mon – Fri 09:00 – 19:00 · Sat 10:00 – 14:00",
    "footer.tagline": "Certified specialists, modern equipment, accessible facilities.",
    "footer.legal": "Reg. No. 40203117924",
    "form.name": "Name",
    "form.phone": "Phone",
    "form.email": "E-mail",
    "form.service": "Service",
    "form.doctor": "Doctor",
    "form.date": "Preferred date",
    "form.time": "Time",
    "form.note": "Notes (optional)",
    "form.consent": "I agree to my data being used to contact me about the visit.",
    "form.submit": "Book the visit",
    "form.next": "Next",
    "form.back": "Back",
    "form.from": "from",
    "form.priceFrom": "Price from",
    "form.req": "This field is required",
    "form.phoneInvalid": "Check the phone number",
    "form.emailInvalid": "Check the e-mail address",
    "form.success": "Thank you! We'll be in touch shortly.",
    "form.step": "Step",
    "form.of": "of",
    "form.selService": "Which service do you need?",
    "form.selDoctor": "Which specialist?",
    "form.selWhen": "When works for you?",
    "form.contact": "How can we reach you?",
    "form.any": "Any",
    "search.placeholder": "Search the price list…",
    "pricing.eyebrow": "Price list",
    "pricing.title": "Transparent prices, no hidden fees.",
    "pricing.lead": "The final price is confirmed after a free consultation and diagnostics.",
    "pricing.note": "All prices are in euros (€). Insured patients are billed directly through the insurer.",
    "services.eyebrow": "Services",
    "services.title": "Everything your smile needs.",
    "services.lead": "Detailed description of each procedure and starting prices.",
    "team.eyebrow": "Team",
    "team.title": "The people taking care of you.",
    "team.lead": "Certified specialists with international experience.",
    "contacts.eyebrow": "Contacts",
    "contacts.title": "Come visit or reach out online.",
    "contacts.lead": "We're in Riga, easy to reach by public transport.",
    "yearsClinic": "years at the clinic",
    "doctorMore": "More about the specialist",
    "acuteBanner": "Acute dental pain: weekdays 12:00 – 14:00",
    "acuteCall": "Call now",
    "lang.label": "Language",
  }
};

Object.assign(window, { SERVICES, TEAM, PRICING, FAQ, REVIEWS, TECH, INSURERS, NEWS, STRINGS });
